const youTUbeLanguage = {
    header: {
        ru: {
            inputPlaceholder: "Введите запрос",
            youTubeTv: "YouTube TV",
            youTubeMusic: "YouTube Music",
            youTubeChild: "YouTube Детям",
            youTubeArtist: "YouTube для музыкантов",
            loginUserYouTubeAccount: "Зарегистрироваться",
            chanelUser: "Мой канал",
            switchUser: "Сменить аккаунт",
            loginUser: "Выйти",
            themeUser: "Тема:",
            themeNameUser: "Тема",
            themeAboutUser: "Настройка будет применена только в этом браузере.",
            themeUserLight: "Светлая",
            themeUserDark: "Тёмная",
            languageUser: "Язык",
            locationUser: "Страна",
            locationNameUser: "Выберите страну",
            dataUser: "Личные данные на YouTube",
            keyboardUser: "Быстрые клавиши",
        },
        uz: {
            inputPlaceholder: "Qidiruv",
            youTubeTv: "YouTube TV",
            youTubeMusic: "YouTube Music",
            youTubeChild: "YouTube Kids",
            youTubeArtist: "Ijrochilar uchun YouTube",
            loginUserYouTubeAccount: "Ro'yxatdan o'tish",
            chanelUser: "Kanalingiz",
            switchUser: "Hisobni almashtirish",
            loginUser: "Chiqish",
            themeUser: "Mavzu rangi:",
            themeNameUser: "Mavzu rangi",
            themeAboutUser: "Faqat shu brauzerga tatbiq qilinadi",
            themeUserLight: "Kunduzgi mavzu",
            themeUserDark: "Tungi mavzu",
            languageUser: "Til",
            locationUser: "Mamlakat",
            locationNameUser: "Mamlakatingizni tanlang",
            dataUser: "YouTubedagi ma'lumotlaringiz",
            keyboardUser: "Klaviatura tezkor tugmalari",
        },
        eng: {
            inputPlaceholder: "Search",
            youTubeTv: "YouTube TV",
            youTubeMusic: "YouTube Music",
            youTubeChild: "YouTube Kids",
            youTubeArtist: "YouTube for Artists",
            loginUserYouTubeAccount: "Sign up",
            chanelUser: "Your channel",
            switchUser: "Switch account",
            loginUser: "Sign out",
            themeUser: "Appearance:",
            themeNameUser: "Appearance",
            themeAboutUser: "Setting applies to this browser only",
            themeUserLight: "Light theme",
            themeUserDark: "Dark theme",
            languageUser: "Language",
            locationUser: "Location",
            locationNameUser: "Location",
            dataUser: "Your data in YouTube",
            keyboardUser: "Keyboard shortcuts",
        },
    },

    navbar: {
        ru: {
            homeLang: "Главная",
            exploreLang: "Навигатор",
            shortsLang: "Shorts",
            subscriptionsLang: "Подписки",
            libraryLang: "Библиотека",
            historyLang: "История",
            watchLaterLang: "Смотреть позже",
            subscribeNameLang: "ПОДПИСКИ",
            likedVideosLang: "Понравившиеся",
            addChannelLang: "Каталог каналов",
            youTubeInfolang: "ДРУГИЕ ВОЗМОЖНОСТИ",
            gamingLang: "Видеоигры",
            liveLang: "Трансляции",
            musicLang: "Музик",
            sportLang: "Спорт",
            creatorLang: "Создатель",
            createTime: "Создано с 2022:03 по 2022:04",
            ceratorLinkedIn: "Создатель LinkedIni",
            creatorGitHub: "Создатель GitHubi"
        },
        uz: {
            homeLang: "Asosiy",
            exploreLang: "Tanishuv",
            shortsLang: "Shorts",
            subscriptionsLang: "Obunalar",
            libraryLang: "Kutubxona",
            historyLang: "Tomosha tarixi",
            watchLaterLang: "Keyinroq",
            subscribeNameLang: "OBUNALAR",
            likedVideosLang: "Yoqqan videolar",
            addChannelLang: "Kanallar katalogi",
            youTubeInfolang: "YouTube xizmatlari",
            gamingLang: "O'yin",
            liveLang: "Jonli efir",
            musicLang: "Music",
            sportLang: "Sport",
            creatorLang: "Yaratuvchi",
            createTime: "2022:03 dan 2022:04 gacha yaratilgan",
            ceratorLinkedIn: "Yaratuvchi LinkedIni",
            creatorGitHub: "Yaratuvchi GitHubi"
        },
        eng: {
            homeLang: "Home",
            exploreLang: "Explore",
            shortsLang: "Shorts",
            subscriptionsLang: "Subscriptions",
            libraryLang: "Library",
            historyLang: "History",
            watchLaterLang: "Watch later",
            subscribeNameLang: "SUBSCRIPTIONS",
            likedVideosLang: "Liked videos",
            addChannelLang: "Browse channels",
            youTubeInfolang: "MORE FROM YOUTUBE",
            gamingLang: "Gaming",
            liveLang: "Live",
            musicLang: "Music",
            sportLang: "Sport",
            creatorLang: "Creator",
            createTime: "Created from 2022:03 to 2022:04",
            ceratorLinkedIn: "Creator LinkedIni",
            creatorGitHub: "Creator GitHubi"
        },
    },
}

export default youTUbeLanguage